name: Action Tests

on:
  push:
    branches:
    - main
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        hugo-preproc-version: [v1.2.0, v2.0.0]
    steps:
    - name: Checkout
      uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

    - name: Setup hugo-preproc
      uses: ./
      with:
        hugo-preproc-version: ${{ matrix.hugo-preproc-version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Verify hugo-preproc version installed
      run: |
        export HUGOPREPROC_VERSION=$( hugo-preproc --version | awk '{print "v" $3}' )
        if [ "$HUGOPREPROC_VERSION" != ${{ matrix.hugo-preproc-version }} ]; then
          echo "error: hugo-preproc version ${{ matrix.hugo-preproc-version }} expected; got $HUGOPREPROC_VERSION"
          exit 1
        fi
        echo "hugo-preproc $HUGOPREPROC_VERSION installed successfully."
